### ISSUE TITLE
[BUG] EFI Boot Entry not installed

### ISSUE THREAD

**Issue by madonuko** [FyraLabs/readymade#32] opened 2024-12-26 10:39 UTC
even though supposedly the kernel package generates the entry during postscript, and we also invoke `kernel-install` inside `backend/postinstall/reinstall_kernel.rs`, non of these attemps actually successfully install the EFI boot entry according to testers.

One way to explain this is that maybe the kernel package installation actually does not generate the boot entry for the new system but instead for the current host system; and `kernel-install` does not actually generate any entries at all.

**Comment by korewaChino** [comment] 2024-12-26 11:07
cant reproduce, it generates when the firmware finds and loads the bootloader for the first time

**Comment by korewaChino** [comment] 2024-12-26 12:16
todo: call `efibootmgr` to create an EFI boot entry within the firmware

**Comment by korewaChino** [comment] 2024-12-29 20:28
Should be fixed as of https://github.com/FyraLabs/readymade/commit/4a90401d3aeebdda8fa63bdb479006580f6d623b

**Closed by korewaChino** 2024-12-29 20:28 UTC
Labels: bug
